print('Введите имя:')
x = input()
print('Ввод фамилии:')
y = input()
print('Ввод возраста:')
w = input()
print('Ввод места жительства:')
z = input()
print(y + " " + x + '\n' + w + '\n' + "Вы живете в " + z) 